### ISSUE TITLE
Add crypto library

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/awesome-gleam#10]
https://github.com/midas-framework/crypto

Not sure what section it belongs under.
Also I would happily transfer it it the gleam-lang organisation if that is of interest?

**Comment by lpil** [comment]
I guess we could make a new Cryptography section?

**Comment by CrowdHailer** [comment]
I'd still like to contribute this library to gleam-lang or even gleam-experiments, because I have written it as a module under the gleam namespace, but I guess no hurry on this front.

**Comment by lpil** [comment]
gleam-experiments sounds good! Is there a github was to transfer it?

**Comment by CrowdHailer** [comment]
I thought I just clicked on the transfer repo button in settings, but doesn't seem to work for organisations.

**Comment by CrowdHailer** [comment]
Ok I can transfer it to you the individual and you'll be able to transfer it to gleam-experiments.

There is an open invite if you want to do that. otherwise ignore it I guess

**Comment by lpil** [comment]
Aha! Thanks!
