### ISSUE TITLE
Rate limiting library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/awesome-gleam#109]

**Comment by nootr** [comment]
Hi @lpil!

Thanks for Gleam, I'm really enjoying it (and the community!) so far.

I've built [a small rate limiting library](https://github.com/nootr/glimit). It's a work in progress as I'm still thinking about its API and some of the code could be optimized, but I'm planning on turning it into something production ready :)

**Comment by lpil** [comment]
Nice! It would be good to document the storage you've used so folks can understand the constraints and applicable use cases.

There's also these libraries too: https://packages.gleam.run/?search=crabbucket

Thank you
