### ISSUE TITLE
Fully type checked PosgreSQL client

### ISSUE THREAD

**Issue by lpil** [gleam-lang/awesome-gleam#139]

**Comment by hfjallemark** [comment]
Are you thinking something like https://github.com/launchbadge/sqlx and its "compile-time checked queries" here @lpil? Any plans on how to implement it? This is my most wanted Gleam feature and will definitely help out (but some direction needed!).

**Comment by lpil** [comment]
Yes that's right, and one should be released soon!

**Comment by hfjallemark** [comment]
Did some digging in the Discord channels and found the demo @giacomocavalieri shared.. awesome stuff! Now I will play around with squirrel 😄

**Comment by giacomocavalieri** [comment]
Ooh yeah I forgot to share I'm working on it here!

**Comment by hfjallemark** [comment]
Played around with it, looks awesome -- just what I've been looking for! Spent last night reading up how sqlx does it using prepared statements and stuff thinking I'd have to build this myself for Gleam but guess I don't have to now 😄 Let me know if there is anything I can help out with 🙏

**Comment by giacomocavalieri** [comment]
This can be closed now that we have [squirrel](https://github.com/giacomocavalieri/squirrel)
