### ISSUE TITLE
Libraries to create

### ISSUE THREAD

**Issue by lpil** [gleam-lang/awesome-gleam#34]
- [x] JSON
- [x] toml
- [x] HTTP types
- [x] Bindings to Erlang web servers
  - [x] Elli
  - [x] Cowboy
- [x] PostgreSQL client
- [x] SQLite client
- [ ] MariaDB / MySQL client
- [x] Password hashing
- [x] Dates + times
- [ ] Currency
- [ ] Email construction and sending
  - [ ] SMTP
  - [x] Various email sending APIs
- [ ] Easy to use Gleam based HTTP client
  - [ ] Out of the box TLS verification
  - [ ] HTTP 1
  - [ ] HTTP 2
  - [ ] Websockets
  - [ ] Manipulates Erlang socket directly to avoid excess data copying between processes
  - [ ] Optional connection pooling
- [x] Gleam based HTTP server
  - [x] HTTP 1
  - [ ] HTTP 2
  - [ ] HTTP 3
  - [x] Websockets
  - [x] Performance competitive with Cowboy
- [ ] Bindings to the Erlang telemetry library
- [x] Binding to Erlang's TCP modules
- [ ] Gleam HTTP CORS
- [x] Gleam HTTP cookies
  - [ ] CSRF protection
  - [x] Signing
  - [ ] Encryption
- [ ] GraphQL server
- [ ] GraphQL client
- [ ] JSON RPC
- [x] Command line options parsing
- [ ] Fuzz testing
- [x] Snapshot testing
- [ ] Property testing
- [ ] Random value generation
- [ ] Temporary files
- [x] CSV (https://github.com/BrianHicks/elm-csv)
- [ ] JS DOM bindings
- [x] JS VDOM
- [ ] JavaScript HTTP server adapter for the Gleam HTTP library
- [ ] XML parsing
- [x] HTML parsing
- [ ] ical parsing + generation
- [ ] Type safe postgresql client using codegen (https://github.com/launchbadge/sqlx/discussions/1925)
- [ ] S3 client
- [ ] Redis client
- [ ] MeiliSearch client
- [x] Logging
- [ ] Metrics collection
- [x] Convention based web framework
- [ ] Generic pattern for collecting multiple errors (https://hackage.haskell.org/package/monad-validate-1.2.0.1/docs/Control-Monad-Validate.html)

**Comment by dropwhile** [comment]
Some other libraries that might be useful to have:
* base32, base64
* protocol buffers
* [twirp rpc](https://github.com/twitchtv/twirp?tab=readme-ov-file#implementations-in-other-languages)

**Comment by lpil** [comment]
Twirp is so cool! I'd love to see that

**Comment by lpil** [comment]
I'm gunna close this as the ecosystem has matured a lot and folks can work out what they need themselves

**Comment by nohehf** [comment]
I think this (maybe in a GitHub wiki tho) is still useful, to coordinate efforts ? WDYT ?

**Comment by David-Klemenc** [comment]
To build Open Api library like [open_api_spex](https://github.com/open-api-spex/open_api_spex) a JSON schema library would be useful.

**Comment by lpil** [comment]
Agreed!
