### ISSUE TITLE
Add icons for targets

### ISSUE THREAD

**Issue by inoas** [gleam-lang/awesome-gleam#51]
If you are interested in this I will find 4 SVG icons for Erlang, Elixir, JavaScript and TypeScript and then we can gradually add icons. If there are none people have to know/investigate, if there are some, the lib/app only works on the given targets?

As Erlang implies it runs on Elixir an Elixir icon would mean that it requires Elixir
As JavaScript implies it would run on TypeScript a TypeScript icon would mean that it requires TypeScript.

We can also just start with one icon for Erlang/Beam and one for JS?

**Comment by lpil** [comment]
I think this would get very noisy! Probably a better one for a future package website.

**Comment by inoas** [comment]
We can add [JS] or [Erlang] tags - still too noisy?
I will close this, in case you want something like this, let me know.
