### ISSUE TITLE
Typo: Under Frontend

### ISSUE THREAD

**Issue by graciasc** [gleam-lang/awesome-gleam#93]
Currently: [lustre_virtual_list](https://github.com/schurhammer/lustre_virtual_list) - [📚](https://hexdocs.pm/lustre_virtual_list/) - A virtual list componenet for lustre.

Update: [lustre_virtual_list](https://github.com/schurhammer/lustre_virtual_list) - [📚](https://hexdocs.pm/lustre_virtual_list/) - A virtual list component for lustre.

The change here is simple; there is a typo on the word component.

**Comment by lpil** [comment]
Thank you
